GET http://localhost:8080/albums

### 

POST http://localhost:8080/albums HTTP/1.1
Host: localhost:8080
Content-Type: "application/json"

{
  "id": "123",
  "title":"Master of Puppets",
  "artist":"Metallica",
  "price": 12.99
}

### Get album by ID
GET http://localhost:8080/albums/1 HTTP/1.1
